apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-application
        image: aapurva/getting-started:v1.0.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000


#---
# Service type is NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: todo
# spec:
#   type: NodePort
#   selector:
#     app: todo
#   ports:
#   - protocol: TCP
#     port: 3000
#     targetPort: 3000
#     nodePort: 30000
    
#---

# Service type is Basic

# apiVersion: v1
# kind: Service
# metadata:
#   name: todo
# spec:
#   selector:
#     app: todo
#   ports:
#   - protocol: TCP
#     port: 3000
#     targetPort: 3000
    
    
---

# Service type is LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  
    
