apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    name: todo-app
spec:
  containers:
  - name: todo-app
    image: aapurva/getting-started:v1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
