apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: namespace-1
  labels:
    name: webapi
spec:
  selector:
    matchLabels:
      type: webapi
  template:
    metadata:
      labels:
        type: webapi
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
            