apiVersion: v1
kind: Namespace
metadata:
  name: wordpressns

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpresswebsite
  namespace: wordpressns
  labels:
    name: wpwebsite
spec:
  containers:
  - name: db
    image: mysql:latest
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "mydb"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: wp-namespace  # Specify the namespace here
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
        - name: wordpress-website
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mydb"
